# Generated by Django 4.1.3 on 2022-11-03 10:11

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('image2', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('image3', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('image4', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('image5', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('image6', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('image7', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('image8', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('image9', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
            ],
        ),
    ]
